zabbix-mysql:
  image: mysql
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/conf:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=Proper123
    - MYSQL_DATABASE=zabbix
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  ports:
    - "3307:3306"
zabbix-server:
  image: zabbix/zabbix-server-mysql
  environment:
    - DB_SERVER_HOST=172.28.235.114
    - DB_SERVER_PORT=3307
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix
  ports:
    - 10051:10051
zabbix-web:
  image: zabbix/zabbix-web-nginx-mysql
  environment:
    - ZBX_SERVER_HOST=172.28.235.114
    - ZBX_SERVER_PORT=10051
    - DB_SERVER_HOST=172.28.235.114
    - DB_SERVER_PORT=3307
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix
    - MYSQL_DATABASE=zabbix
    - TZ=Asia/Shanghai
  ports:
    - 8080:80
