isj-pep1_official:
  image: propersoft/pep
  volumes:
    - ./pep1/tomcat/webapps:/usr/local/tomcat/webapps
    - ./pep1/tomcat/logs:/usr/local/tomcat/logs
  ports:
    - "39091:8080"
  extra_hosts:
    - "his-server:172.28.235.115"
  environment:
    - JAVA_OPTS=-server -XX:PermSize=4096M -XX:MaxPermSize=8192m -Xms4096m -Xmx16384m
isj-pep2_official:
  image: propersoft/pep
  volumes:
    - ./pep2/tomcat/webapps:/usr/local/tomcat/webapps
    - ./pep2/tomcat/logs:/usr/local/tomcat/logs
  ports:
    - "39092:8080"
  extra_hosts:
    - "his-server:172.28.235.115"
  environment:
    - JAVA_OPTS=-server -XX:PermSize=4096M -XX:MaxPermSize=8192m -Xms4096m -Xmx16384m
isj-properpush_official:
  image: propersoft/pep-isj
  volumes:
    - ./properpush/tomcat/webapps:/usr/local/tomcat/webapps
    - ./properpush/tomcat/logs:/usr/local/tomcat/logs
  ports:
    - "35555:9090"
  environment:
    - JAVA_OPTS=-server -XX:PermSize=512M -XX:MaxPermSize=2048m -Xms512m -Xmx4096m
isj-mongo_official_cf1:
  image: mongo
  volumes:
    - ./mongo_cf1/data:/data/db
    - ./mongo_cf1/keyfile:/opt/keyfile
  ports:
    - "37101:27017"
  command: mongod --configsvr --keyFile /opt/keyfile/mongodb-keyfile --replSet cf --port 27017
isj-mongo_official_rs1_1:
  image: mongo
  volumes:
    - ./mongo_rs1_1/data:/data/db
    - ./mongo_rs1_1/keyfile:/opt/keyfile
  ports:
    - "37011:27017"
  command: mongod --keyFile /opt/keyfile/mongodb-keyfile --replSet rs1
isj-mongo_official_rs2_3:
  image: mongo
  volumes:
    - ./mongo_rs2_3/data:/data/db
    - ./mongo_rs2_3/keyfile:/opt/keyfile
  ports:
    - "37023:27017"
  command: mongod --keyFile /opt/keyfile/mongodb-keyfile --replSet rs2
isj-redis1_official:
  image: redis
  net: host
  volumes:
    - ./redis1/data:/data
    - ./redis1/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
isj-redis2_official:
  image: redis
  net: host
  volumes:
    - ./redis2/data:/data
    - ./redis2/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
isj-nginx_official:
  image: nginx
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/log:/var/log/nginx
  ports:
    - "8099:80"
