INSERT INTO pep_auth_roles_menus (role_id, menu_id) VALUES ('role-kf', 'app-yjfk');
INSERT INTO pep_auth_roles_menus (role_id, menu_id) VALUES ('role-xxwh', 'app-wxts');
INSERT INTO pep_auth_roles_menus (role_id, menu_id) VALUES ('role-xxwh', 'app-yydh');
INSERT INTO pep_auth_roles_menus (role_id, menu_id) VALUES ('role-xxwh', 'app-lbtp');
INSERT INTO pep_auth_roles_menus (role_id, menu_id) VALUES ('role-xxwh', 'app-ghgz');
INSERT INTO pep_auth_roles_menus (role_id, menu_id) VALUES ('role-kf', 'app-ywtj');
INSERT INTO pep_auth_roles_menus (role_id, menu_id) VALUES ('role-xxwh', 'app-ywtj');
INSERT INTO pep_auth_roles_menus (role_id, menu_id) VALUES ('role-xxwh', 'app-apppz');
INSERT INTO pep_auth_roles_menus (role_id, menu_id) VALUES ('role-xxwh', 'app-tomcat-log');
COMMIT;